general:
  initial_frame: 0            # frame of the data to start with
  final_frame: 120            # frame of the data to end with
  verbose: False              # print additional information for each iteration of PICP
  save_results: True          # save plot of the results of each frame
  save_icp_plots: False       # save the results of the PICP iterations (warning: can be very slow)
  save_icp_plots_indices: []  # save plots of the PICP iterations for the specified indices


picp:

  # kernel threshold used to reject outliers
  base_kernel_threshold: 1000 # initial threshold for the kernel
  min_kernel_threshold: 10    # minimum threshold for the kernel
  max_kernel_threshold: 2000  # maximum threshold for the kernel

  # dumping factor used to update the pose. The larger the factor, the less the pose is updated
  base_dumping_factor: 64     # initial dumping factor
  min_dumping_factor: 1       # minimum dumping factor
  max_dumping_factor: 64      # maximum dumping factor

  min_inliers: 20             # minimum number of inliers to consider the pose as valid

  num_iterations: 250         # maximum number of iterations for the PICP algorithm